modLoader="javafml"
loaderVersion="[41,)"
license="MIT"
issueTrackerURL="https://github.com/itsmeow/QuickTeleports/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/quickteleports"
logoFile="quickteleports.png"
credits="itsmeowdev, for programming, ideas, design, and leading, TheKuba for porting and changing the script to fit his needs"
authors="itsmeowdev"
[[mods]]
modId="quickteleports"
version="${version}"
displayName="LongTeleports"
description='''
This mod adds a quick and easy way to send tp requests with /tpa and /tpaccept'''
[[dependencies.quickteleports]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.0,)"
    ordering="NONE"
    side="SERVER"